### ISSUE TITLE
Ambiguity when searching for materials docs for task_ids

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#108]
I'm interpreting `task_ids` as "return a list of material docs that have `task_id` in this comma-delimited list of task_ids", i.e. it does *not* query `task_ids`.

However, there's also the `task_ids` field in the materials doc itself, how do we query this? Or is a query for `task_id` querying `task_ids` by default?

**Comment by munrojm** [comment]
Ah, yes I see the confusion. Currently, `task_ids` takes a list of ids and returns docs which have any of those within the `task_ids` field. It does not return a list of material docs that have `task_id` equal to the ones in the list. The query looks like this: `{"task_ids": {"$in": task_ids.split(",")}}`

My thought was if you wanted the latter, you would just use the `/materials/{task_id}` route multiple times to pull individual docs.
