### ISSUE TITLE
Max delta volume filter not working for insertion electrodes

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#226]
The `delta_volume`min and max params are not working. Could be related to `max_delta_volume` returning a string instead of a number.

Example query: `https://api.materialsproject.org/insertion_electrodes/?delta_volume_min=3&skip=0&limit=10&all_fields=false
`

**Comment by jmmshn** [comment]
The data on atlas has been updated so this should work now

**Comment by munrojm** [comment]
@codytodonnell this appears to be working now. Once you confirm, I will close the issue.
