### ISSUE TITLE
Stability filter params not working for insertion electrodes

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#227]
The `stability_charge` and `stability_discharge` min and max params are not working.

Example query: `https://api.materialsproject.org/insertion_electrodes/?stability_discharge_min=100&skip=0&limit=10&all_fields=false
`

**Comment by jmmshn** [comment]
The data looks like it's all there I'm not 100% sure what is causing this.

**Comment by munrojm** [comment]
@codytodonnell this also appears to be working now. Once you confirm, I will close the issue.
