### ISSUE TITLE
Add elements/formula filters to electrodes endpoint

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#228]
To keep the Batteries Explorer consistent with the Materials/Molecules Explorers, it would be good to let users search for batteries by supplying a list of elements or a formula.

It would be ideal if this list could be be interpreted as "includes at least" or "includes only." The materials endpoint achieves this by allowing chemsys values to be passed to the `formula` param (e.g. Si-O).

**Comment by jmmshn** [comment]
https://github.com/materialsproject/api/pull/229. 
This PR added the elements field as a list, is having it in chemsys format easier to work with?

**Comment by codytodonnell** [comment]
It would be easiest to have both. I see these in the `InsertionElectrodeDoc` but not in the params. Can elements/chemsys be added to the params too?

**Comment by jmmshn** [comment]
@munrojm I'm not sure where that code lives.

**Comment by munrojm** [comment]
I can add support for the queries if the data is in the doc.

**Comment by jmmshn** [comment]
The data on atlas has the required fields now

**Comment by munrojm** [comment]
Okay, I will it now.

**Comment by jmmshn** [comment]
Thanks!
