### ISSUE TITLE
Switch to emmet models causing validation failures, client to fail

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#265]
Observed separate issues in `materials` and `thermo`, but might affect more endpoints. 

1. An example with `materials`:

```
from mp_api.matproj import MPRester
with MPRester() as mpr:
    docs = mpr.materials.search(chunk_size=1, num_chunks=1)
```

leads to:

```
ValidationError: 1 validation error for MaterialsCoreDoc
symmetry -> crystal_system
  value is not a valid enumeration member; permitted: 'triclinic', 'monoclinic', 'orthorhombic', 'tetragonal', 'trigonal', 'hexagonal', 'cubic' (type=type_error.enum; enum_values=[<CrystalSystem.tri: 'triclinic'>, <CrystalSystem.mono: 'monoclinic'>, <CrystalSystem.ortho: 'orthorhombic'>, <CrystalSystem.tet: 'tetragonal'>, <CrystalSystem.trig: 'trigonal'>, <CrystalSystem.hex: 'hexagonal'>, <CrystalSystem.cubic: 'cubic'>])
```

This is the result, I think, of the symmetry field being capitalized in the returned data.

2. An example with `thermo`:

```
from mp_api.matproj import MPRester
with MPRester() as mpr:
    docs =  mpr.thermo.search(energy_above_hull_max=0.2, num_chunks=1, chunk_size=1, fields=["energy_above_hull"])
```

leads to:

```
ValidationError: 6 validation errors for ThermoDoc
material_id
  field required (type=value_error.missing)
uncorrected_energy_per_atom
  field required (type=value_error.missing)
energy_per_atom
  field required (type=value_error.missing)
energy_type
  field required (type=value_error.missing)
entry_types
  field required (type=value_error.missing)
entries
  field required (type=value_error.missing)
```

This seems to be a broader issue of emmet docs requiring fields be present, but API docs wanting to be permissive with fields being empty.

**Comment by munrojm** [comment]
@mkhorton, thanks for bringing this up. This appears to be an issue with the emmet model transition not being properly propagated through to some of the rester clients. I'll take a closer look and ping you when it is fixed.

**Comment by munrojm** [comment]
Just pushed a fix to `main` after testing your examples. The issue appears to be solved now.

**Comment by mkhorton** [comment]
Thanks! Closed with 6aa2c0a885aab292835023f63c19394c4aff0d78

Btw think a stray print statement snuck in in core/resource.py

**Comment by mkhorton** [comment]
Related, the `dielectric` document has changed -- the `static` part has disappeared completely, though I can see it's still in the database document on Atlas. It seems like maybe it was renamed at some point: https://github.com/materialsproject/emmet/blob/56f38b3f59d89264fdb8eb6d912281e193973d67/emmet-core/emmet/core/polar.py#L100

@shyamd can you comment on the changes? Is this something that requires a re-build to fix?

@codytodonnell, @tschaume the dielectric section on the detail page will be out of action until this is resolved, so disregard any callback errors

**Comment by munrojm** [comment]
This issue has been fixed with data patching.
