### ISSUE TITLE
Some mp-ids do not return results from the client

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#311]
Some mp-ids that are returned from the /search endpoint cannot be found using the `mpr.materials.get_document_by_id()` method.

Example of error returned:

> mp_api.core.client.MPRestError: No result for record mp-1142593.

List of mp-id culprits found so far:
- mp-1142593
- mp-1146179

**Comment by munrojm** [comment]
This will be solved soon by a data fix. I will close the issue when those entries are updated.
