### ISSUE TITLE
Strange pagination behavior with stability filter and energy sort

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#325]
If the following params are active: `is_stable=true` and `sort_field=energy_above_hull` and `ascending=false`, then some of the same results will appear on multiple pages.

For example, the last seven results in the following two queries are the same:

https://api.materialsproject.org/search/?limit=15&skip=150&sort_field=energy_above_hull&ascending=false&is_stable=true

and

https://api.materialsproject.org/search/?limit=15&skip=165&sort_field=energy_above_hull&ascending=false&is_stable=true

So far, I have only seen this behavior with these exact params.

**Comment by munrojm** [comment]
So it looks because `is_stable = True`, this problem is due to the fact mongo is trying to sort in descending order based on a field that has a value of zero (energy above hull) for all of the entries.
