### ISSUE TITLE
Allow chemical system searches for molecules

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#332]
At the moment, you can only search for molecules by elements (e.g. H,C,N) or formula (e.g. H10C5N) but you cannot search by chemical system (e.g. H-C-N).

It would be good to support this for consistency across explorer endpoints and apps.

**Comment by munrojm** [comment]
Since a `chemsys` field is not present for the molecules, is it possible for you to just translate it into an `elements` and `elements_exclude` query? I believe I will have to add support for the latter field to the endpoint.

**Comment by codytodonnell** [comment]
This is technically possible. If I applied this same logic to the other endpoints too, would that cause any performance issues? It would be preferable to keep the logic between SearchUI's as consistent as possible.

**Comment by munrojm** [comment]
Fair enough, let me do it server side then.
