### ISSUE TITLE
Fix id sort behavior

### ISSUE THREAD

**Issue by codytodonnell** [materialsproject/api#334]
Currently, an ascending sort by material_id will return:
`[mp-1, mp-10, mp-100, mp-1000, mp-10000, mp-10001...]`

It would be preferable if the API would sort by the number after the id prefix. So the above sort would instead return:
`[mp-1, mp-2, mp-3, mp-4...]`

**Comment by munrojm** [comment]
With MongoDB sorting, this is a tricky problem without fully implementing aggregation pipelines across all endpoint types. For now, the solution might have to be a patch that sorts again server-side once the data is pulled, and if `material_id` is present and selected as the sort field.
