### ISSUE TITLE
`get_entries_in_chemsys` has 6x slower performance

### ISSUE THREAD

**Issue by mattmcdermott** [materialsproject/api#363]
The `MPRester` implemented in the new API has significantly slower performance for downloading entries in a chemical system:

Take the code below:

```python
with mp_api.matproj.MPRester() as mpr:
    entries = mpr.get_entries_in_chemsys("Y-Mn-O")
```

This runs in **3.8 seconds**. With the old API, this completes in **0.6 seconds**. This is around a 6x slower performance. 

This issue also seems to scale similarly in larger chemical systems.

**Comment by mkhorton** [comment]
Good catch!

I notice that `get_entries` does a server-side sort that perhaps might be done better client-side, though the difference isn't really significant within the error so I _do not_ think this is the culprit:

```
%timeit results = mpr.thermo.search_thermo_docs(chemsys_formula="Y-Mn-O", all_fields=False, fields=("entries",), sort_field="energy_above_hull", ascending=True)
# 439 ms ± 123 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit results = mpr.thermo.search_thermo_docs(chemsys_formula="Y-Mn-O", all_fields=False, fields=("entries",))
# 366 ms ± 117 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

Tested on Si-O too, definitely a substantial difference:

```
%timeit results = mpr.thermo.search_thermo_docs(chemsys_formula="Si-O", all_fields=False, fields=("entries",))
# 2.54 s ± 153 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

%timeit results = mpr.get_entries('Si-O')  # old
# 362 ms ± 14.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

So Si-O might be a good one to concentrate on to optimize.

I was intentionally calling the low-level search methods here rather than the convenience methods to make it easier to profile.

**Comment by munrojm** [comment]
After some investigating, this appears to be caused by a bottleneck from serialization and/or deserialization. Queries on the backend are very fast. I will update here once I have implemented a solution.

**Comment by mkhorton** [comment]
Related to serialization, I briefly investigated adding support for using `orjson` in `monty` but the API for `json.loads()` etc. was not exactly the same so it didn't work as a drop-in replacement. Seemed doable, but might have required a bit extra effort.

**Comment by mattmcdermott** [comment]
@munrojm Was wondering if you have had any luck with fixing this issue? This is the only thing holding me back from using the new API and I imagine it might be that way for others too.

**Comment by munrojm** [comment]
@mattmcdermott thanks for following up. I don't have an update yet, but I will put this on my priority list for this week.

**Comment by mkhorton** [comment]
Any further info on this @munrojm, related to the hinting?

**Comment by munrojm** [comment]
I have investigated this a bit more. Currently, it looks like a fundamental limitation on the database side. The majority of the slowdown appears to be from a speed difference in the raw individual `chemsys` queries (even with proper hints).

I am going to try adding a query parameter that can accept multiple values of `chemsys` natively to speed things up.

**Comment by mkhorton** [comment]
@munrojm how is the current API that much faster then, given that both are backed by MongoDB? Not sure I understand the outline of this problem.

**Comment by munrojm** [comment]
Initial tests of asynchronous requests within the client fix this problem and bring the total time down to ~0.6-0.8 sec. I am still wrestling with how to implement the feature properly, but it should be in soon.

**Comment by munrojm** [comment]
`v0.20.0` of the API solves this issue. There is still a tiny bit of room for optimization, but the method call now returns data in ~0.7-0.9 sec.

**Comment by mkhorton** [comment]
What a nice issue to close :) Thanks for all the hard work on this @munrojm!

**Comment by munrojm** [comment]
Thanks @mkhorton !!

**Comment by mattmcdermott** [comment]
Thank you so much @munrojm! Very happy to finally switch over now :)
