### ISSUE TITLE
Tasks API Request

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#46]
Opening as a separate issue so as not to overlap with core.

We'll need a Tasks API to mirror the current one, see [tasks detail page](https://www.materialsproject.org/tasks/mp-804) for an example, and also the [`.get_task_data()`](https://pymatgen.org/pymatgen.ext.matproj.html#pymatgen.ext.matproj.MPRester.get_task_data) method.

Ideally we'd like to mirror what we offered historically, but maybe we can tweak it slightly:

- [x] Output structure, input structure
- [x] Standard output structure-derived fields, e.g. space group (straight from task doc)
- [x] Standard energy outputs
- [x] Incar/kpoints/potcar spec
- [x] *new* Trajectory for relaxation (see pymatgen Trajectory class), annotated with forces if available ... can talk about this, not sure if we'd want energy per frame too (I think the class supports this)

The last can enable a much more fun task details page so I'm excited about it.

**Comment by munrojm** [comment]
@mkhorton, would you prefer to have the trajectory data come from it's own endpoint, or do you want the heavy lifting to be done client-side after getting the data in `calcs_reversed`?

**Comment by mkhorton** [comment]
@munrojm last time I looked into this the Trajectory was significantly smaller in size than a list of Structures, so from its own endpoint ideally.

**Comment by munrojm** [comment]
> @munrojm last time I looked into this the Trajectory was significantly smaller in size than a list of Structures, so from its own endpoint ideally.

I just added a new trajectories endpoint that returns lists containing pymatgen Trajectory objects for each calculation listed in the `calcs_reversed` field of a task document.

**Comment by mkhorton** [comment]
Fantastic :) I see it.

Given that there are a lot of endpoints now, do you have thoughts on naming conventions? e.g. should this be `tasks_trajectory` or `tasks/trajectory/` or ...? Not sure how best to organize.

**Comment by munrojm** [comment]
The second is more involved given how some of the code is structured. If you wanted "tasks" in the name, the first would be easiest for the moment.

**Comment by mkhorton** [comment]
I'm thinking more in general if we want to have some conventions, and what they might look like, e.g. are all properties going to be top-level too? `/eos` `/elastic` or `/property/eos` `/property/elastic`? We can open a dedicated issue to discuss if preferred.

For now, as it is currently is absolutely fine.

**Comment by munrojm** [comment]
Ah, okay I see. Yeah, a dedicated issue might be good just to keep things organized.

**Comment by mkhorton** [comment]
Looks like we can close this issue! 🎉 Thank you.

**Comment by munrojm** [comment]
Sounds good! I just realized I will have to add support for passing a single `task_id` to the client method. Will do that now.

**Comment by mkhorton** [comment]
I have a few more requests for this one, based on `calcs_reversed`, it would be helpful to show `vasp_version` and also `calcs_reversed.inputs`, and at the top-level, `completed_at`, possibly `custodian`, `analysis`. Offline we should check-in about sandboxing too.

**Comment by mkhorton** [comment]
In addition, being able to search `tasks` with a list of task ids in the same way as the materials end-point would be useful: I'm trying to determine which tasks are available and which are not, or retrieve information from multiple tasks simultaneously.

**Comment by munrojm** [comment]
> In addition, being able to search `tasks` with a list of task ids in the same way as the materials end-point would be useful: I'm trying to determine which tasks are available and which are not, or retrieve information from multiple tasks simultaneously.

Given my response in #108 do you want to add this functionality to both?

**Comment by mkhorton** [comment]
Yes, that would be ideal thanks, e.g. a `task_id` search term.

I tried the approach of pulling multiple documents but it's noticeably slow

**Comment by munrojm** [comment]
> I have a few more requests for this one, based on `calcs_reversed`, it would be helpful to show `vasp_version` and also `calcs_reversed.inputs`, and at the top-level, `completed_at`, possibly `custodian`, `analysis`. Offline we should check-in about sandboxing too.

This is done and will be pushed to release soon.

**Comment by mkhorton** [comment]
Great, thanks!!
