### ISSUE TITLE
Typo: `get_materials_id_from_task_id`

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#529]

**Comment by munrojm** [comment]
I assume you mean `materials` -> `material`?

**Comment by mkhorton** [comment]
Yes! Apologies, created this issue via the project board, and didn't fill in all the context.

**Comment by munrojm** [comment]
No worries. The methods in the previous `MPRester` have the same spelling. If we make this change, we will lose backwards compatibility.

**Comment by mkhorton** [comment]
I think we've already lost backwards compatibility in other areas, better to be correct?

**Comment by munrojm** [comment]
Every top level convenience method in the new MPRester with the same name is currently backwards compatible. With most people having to move away from `query` I think changing these now is reasonable.

**Comment by mkhorton** [comment]
We can keep the old name and add a deprecation warning too

**Comment by munrojm** [comment]
Sure thing, I'll add that.

**Comment by munrojm** [comment]
Fixed in this [branch](https://github.com/materialsproject/api/tree/enhance_usability). Will be merged after we finalize model details.
