### ISSUE TITLE
ISSUE: Unable to query trajectories

### ISSUE THREAD

**Issue by BowenD-UCB** [materialsproject/api#541]
Hi,
I'm trying to query trajectories(DFT Ionic Relaxtion Steps) from MP.
But
mpr.tasks.get_trajectory(task_id='mp-925998')
returns me None
Same query is successful on the web API
https://api.materialsproject.org/docs#/Tasks/get_by_key_tasks_trajectory__task_id___get
![Screen Shot 2022-02-28 at 4 09 59 PM](https://user-images.githubusercontent.com/84425382/156080166-ab9eb705-3006-4e11-a57c-576817a54263.png)

**Comment by munrojm** [comment]
Thank you for the heads up on this @BowenD-UCB. In response, I have fixed this in #542 and will patch release the API very soon. Will ping you here again when that is done.

**Comment by munrojm** [comment]
This is fixed as of `v0.21.1`
