### ISSUE TITLE
TASK.trajectories

### ISSUE THREAD

**Issue by BowenD-UCB** [materialsproject/api#549]
Hi,
mpr.tasks.get_trajectory returns only 2 ionic steps for each tasks.
I suppose it is only returning the converged entry in each relaxation?

<img width="789" alt="Screen Shot 2022-03-07 at 4 26 45 PM" src="https://user-images.githubusercontent.com/84425382/157141295-2729cec9-2bf1-45d5-98a6-9dde339895a9.png">

**Comment by munrojm** [comment]
Sorry for such a delayed response to this. This is fixed in https://github.com/materialsproject/emmet/pull/382 which should be merged shortly.
