### ISSUE TITLE
MoleculesDoc import issue

### ISSUE THREAD

**Issue by mbagheri20** [materialsproject/api#597]
Hi,

I tried to install the new version with pip and the installation in a virtual environment was successful but when I imported MPRester from mp_api following error returned:

`ImportError: cannot import name 'MoleculesDoc' from 'emmet.core.molecules'`

**Comment by munrojm** [comment]
I am hot fixing this now. Will patch release today.

**Comment by munrojm** [comment]
This should be fixed as of the latest release.
