### ISSUE TITLE
pip install mp_api not working

### ISSUE THREAD

**Issue by vinven7** [materialsproject/api#603]
Not able to install mp_api using pip:

```
pip install mp_api
ERROR: Could not find a version that satisfies the requirement mp_api
ERROR: No matching distribution found for mp_api
```

python 3.6.13
NAME="Rocky Linux"                                                                                                     
 VERSION="8.4 (Green Obsidian)"

**Comment by munrojm** [comment]
Hi @vinven7, unfortunately the client only officially supports python 3.8 and up. If you want to pip install the package, you will have to update your installation.
