### ISSUE TITLE
Task Deprecation API

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#63]
This doesn't come directly from the tasks doc iirc so should probably be a separate endpoint.

Ideally, this would return a simple `{deprecated: true/false, deprecation_reason: str}`

(Under the current build process, deprecation reason will have to be empty) 

- [x] Endpoint added
- [x] Add ability to query with a list of task_ids

**Comment by mkhorton** [comment]
Actually, having this be part of the materials endpoint probably makes sense, since this is where the other deprecated task information is held.

**Comment by munrojm** [comment]
`deprecated` is currently a field that can be request when querying the materials endpoint. Did you want to have a separate endpoint specifically for obtaining deprecation data?

**Comment by mkhorton** [comment]
This is not the global deprecated true/false but the list of deprecated task_ids, I'm fine with it being part of the materials endpoint though, that seems sensible since it's already in the materials doc.

**Comment by mkhorton** [comment]
The ideal place for this would be part of the tasks endpoint, but this isn't contained in the task doc itself (it's built information), so it's a little tricky.

**Comment by munrojm** [comment]
Oh gotcha, you mean the data in `deprecated_tasks`. I should be able to make a separate endpoint under `tasks` even if it comes from the materials doc.

**Comment by mkhorton** [comment]
I'll defer to your judgement on that. It's tricky because I think the API should reflect the underlying document model as much as possible (to make it more obvious to someone examining the builders etc where that information came from), but this is semantically closer to `tasks` than it is to `materials`, so ???

**Comment by munrojm** [comment]
Yeah, I generally agree with you. I will start with it under the tasks endpoint, and we can always move it later.

**Comment by munrojm** [comment]
Endpoint is added, but `deprecated_tasks` is not currently populated in the `materials.core` collection docs on atlas.

**Comment by mkhorton** [comment]
Is `deprecation_reason` populated yet btw?

**Comment by munrojm** [comment]
No, it isn't but I closed this issue here and opened a new one in the emmet repo since it is a builder problem.

**Comment by mkhorton** [comment]
Perfect, just going to cross-link the issue here for reference: https://github.com/materialsproject/emmet/issues/383
