### ISSUE TITLE
Error in iridium ion data

### ISSUE THREAD

**Issue by gauthierlab** [materialsproject/api#635]
In the ion energy database, specifically for iridate: https://contribs.materialsproject.org/contributions/618b403d96b9dd99c18b2833

-- the charge is erroneously listed as -1, when it should be -2 (see Pourbaix 1966, which is given as the reference in the Brookins textbook).

**Comment by munrojm** [comment]
Just circling back on this now. @rkingsbury I remember asking about this issue a while back. Do you know what the state of the data is?

**Comment by rkingsbury** [comment]
Thanks for the reminder @munrojm ; I have it on my list to fix the charge. I'll try to get to it today or tomorrow.

@gauthierlab , based on our discussion my understanding is that the **value** is correct, just the charge is listed wrong.

**Comment by rkingsbury** [comment]
Done! @tschaume took care of this for us. I believe we can close this issue now. @gauthierlab please let us know if anything still looks amiss (make sure to refresh the page to see the latest data)

**Comment by munrojm** [comment]
@rkingsbury, awesome! Thank you for your help.
