### ISSUE TITLE
Materials Core API

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#64]
Creating a new issue for anything for the core endpoint.

- [ ] `has` it would be useful to have the `has` field (e.g. phonons, band structure, etc.)

**Comment by munrojm** [comment]
Is the intention to keep the `hasprops` collection around?

**Comment by mkhorton** [comment]
@shyamd ?

I think it'd be useful, e.g. for mat details page, I'll load all initial core materials data, and then based on the `has` can determine which other sections to display and what additional rester calls to make.

I could just attempt `get_bandstructure` etc, but I'd have to have N API calls for N properties just to see if they exist.

**Comment by shyamd** [comment]
I was thinking of building a search builder that could be used for search and would index the various properties in collections. The presence of a document could be included.

**Comment by mkhorton** [comment]
Either way, we need a stats endpoint too so this information could possibly be included as part of the search builder too? this is mentioned in #21

**Comment by mkhorton** [comment]
Whats going on with `deprecated` vs `state` in the materials endpoint? Shouldn't these be separate? i.e. a material can be deprecated or not deprecated, and also theoretical or not theoretical?

**Comment by munrojm** [comment]
Yes, there is currently a `deprecated` tag in the data model, but not one to deal with the state. I am working off of the current document schema which does not have a `theoretical` tag.

**Comment by mkhorton** [comment]
It has a `state` tag, it was unclear to me what was in here though (`"Experimental"`?)

**Comment by munrojm** [comment]
I removed the `state` tag as it is not a field in the `materials.core` document structure.

**Comment by mkhorton** [comment]
Got it, thanks!

**Comment by shyamd** [comment]
Should we switch `deprecated` to `valid` ?

**Comment by munrojm** [comment]
Closing this as the data will be part of #115
