### ISSUE TITLE
nelements in search not working

### ISSUE THREAD

**Issue by sean-mcsherry** [materialsproject/api#645]
Hello,

I recently updated to the latest release and noticed my query was not working (see below). It appears the nelements field is not working. 

![image](https://user-images.githubusercontent.com/40900069/181086140-03be26e0-3ab9-4b38-82af-13914f14e21b.png)

**Comment by mkhorton** [comment]
Hi @sean-mcsherry, it would seem like this is `num_elements`:

https://github.com/materialsproject/api/blob/3850b8077fedd43e7db26b02814b0bb34ef6cc75/src/mp_api/routes/summary.py#L66

Perhaps @munrojm can comment on the change?

A note that--while an official release is hopefully very soon--the new API is still aimed at "early adopters" and some breaking changes like this may be expected during this time, but my apologies if this causes inconvenience.

**Comment by janosh** [comment]
Related #614.

**Comment by janosh** [comment]
Also related #683.
