### ISSUE TITLE
Get subset of symmetry data

### ISSUE THREAD

**Issue by janosh** [materialsproject/api#657]
The `symmetry` field (formerly `spacegroup`) used to be associative, meaning if I only want the spacegroup number or just the symbol from

```
SymmetryData(crystal_system=<CrystalSystem.ortho: 'Orthorhombic'>, symbol='Pnma', number=62, point_group='mmm', symprec=0.1, version='1.16.2')
```

I'd do

```py
mp_data = MPRester().query(
    "mp-1234",
    ["material_id", "pretty_formula", "spacegroup.number", "spacegroup.symbol"],
)
```

Is this possible with the new `MPRester`? I tried

```py
from mp_api import MPRester

fields = ["material_id", "symmetry.number"]  # raises 503 error
fields = ["material_id", "symmetry_number"]  # returns None
with MPRester() as mpr:
    docs = mpr.summary.search(fields=fields, material_ids=["mp-1234"])

print(f'{docs[0].symmetry=}')
>>> docs[0].symmetry=None
```

**Comment by munrojm** [comment]
Unfortunately, not at the moment. That syntax was as a result of a tighter coupling between the query syntax and how it translated into MongoDB queries. There is more separation now, resulting in some nested data structures now having to be projected only with their parent field.

**Comment by wuqc970716** [comment]
> Unfortunately, not at the moment. That syntax was as a result of a tighter coupling between the query syntax and how it translated into MongoDB queries. There is more separation now, resulting in some nested data structures now having to be projected only with their parent field.
Then is it not possible at this point to use both the chemical formula and spacegroup number as input to query other properties in the new MPRester?
E.g. in the legacy MPRester I would do
 `m.query(criteria={'pretty_formula':'str','spacegroup.number':int},
                            properties=['structure'])`
Can this be equivalently achieved in the new MPRester?

**Comment by munrojm** [comment]
You can definitely still query with both. You just have to ask for all of the symmetry data and access it as a nested object in the results.

```python
from mp_api import MPRester

with MPRester() as mpr:
    docs = mpr.summary.search(spacegroup_number=227, formula="Si", fields=["material_id", "symmetry"])
```

**Comment by hhh123hhh123** [comment]
@munrojm 
I found your code doesn't work.
According to this website：https://docs.materialsproject.org/downloading-data/using-the-api/examples
We should write：
`from mp_api.client import MPRester

with MPRester(Spark_API) as mpr:
    docs = mpr.summary.search(spacegroup_number=227, formula="Si", fields=["material_id", "symmetry"])
    data = {doc.material_id: doc.symmetry for doc in docs}
data `

**Comment by hhh123hhh123** [comment]
@munrojm 
I found your code doesn't work.
According to this website：https://docs.materialsproject.org/downloading-data/using-the-api/examples
We should write：
`from mp_api.client import MPRester

with MPRester(Spark_API) as mpr:
    docs = mpr.summary.search(spacegroup_number=227, formula="Si", fields=["material_id", "symmetry"])
    data = {doc.material_id: doc.symmetry for doc in docs}
data `

**Comment by hhh123hhh123** [comment]
@munrojm 
I found your code doesn't work.
We should change it to：
```
from mp_api.client import MPRester

with MPRester(Spark_API) as mpr:
    docs = mpr.summary.search(spacegroup_number=227, formula="Si", fields=["material_id", "symmetry"])
    data = {doc.material_id: doc.symmetry for doc in docs}
data 
```
