### ISSUE TITLE
API docs are not up-to-date

### ISSUE THREAD

**Issue by shyuep** [materialsproject/api#683]
Besides the issues I highlighted earlier, there are other issues with the docs being not updated or functionality is broken. For instance, the API docs suggest that using nelements is a perfectly valid way to query. But the following code

```python
mpr.summary.search(nelements=[1], fields=["formula_pretty"])
```

fails with

```
TypeError: search() got an unexpected keyword argument 'nelements'
```

I tried both int and list for nelements and neither worked.

**Comment by janosh** [comment]
@shyuep Where is `nelements` documented? This works:

```py
MPRester(mp_api_key).summary.search(num_elements=1, fields=["formula_pretty"])
```

Looks like the type anno is incorrect though:

https://github.com/materialsproject/api/blob/15c378bc4ccbe19cc2a0e1b8b9b934ea64622e4e/mp_api/client/routes/summary.py#L66

**Comment by shyuep** [comment]
Erm I am no longer responsible for API documentation.
