### ISSUE TITLE
API check / heartbeat

### ISSUE THREAD

**Issue by mkhorton** [materialsproject/api#69]
- [x] End-point to check API is online
- [x] Should return dictionary with currently installed version of API code (not sure if `setuptools-scm` is useful here?), currently installed version of pymatgen, and any other relevant library (eg spglib)

In current MPRester, the current/default DB version is also returned here. Not sure if that would be useful to add or not.

**Comment by munrojm** [comment]
I have added the API version, DB version, and pymatgen version to the heartbeat endpoint.

**Comment by mkhorton** [comment]
Great, thanks!

**Comment by mkhorton** [comment]
To clarify for this issue, that will be the `/heartbeat` endpoint specifically?

**Comment by munrojm** [comment]
Yes, exactly.
