### ISSUE TITLE
Potential circular import

### ISSUE THREAD

**Issue by ryotatomioka** [materialsproject/api#696]
**Steps to reproduce**
```python
from mp_api.client import MPRester
```
raises
> ImportError: cannot import name 'MPRester' from partially initialized module 'mp_api.client' (most likely due to a circular import)

but
```python
import pymatgen
from mp_api.client import MPRester
```
is ok.

**Environment**
 * pymatgen==2022.9.21
 * mp-api==0.29.2

**Comment by munrojm** [comment]
Hi @ryotatomioka, I am not able to recreate the issue in a fresh python 3.8 environment with those two versions installed. Could you provide me more details about your package environment?

**Comment by ryotatomioka** [comment]
Thank you for looking into this. It turns out that my pip environment was broken and I had `pymatgen==2020.12.31` contradicting what `pip show pymatgen` shows.

**Comment by munrojm** [comment]
No problem! Glad it was an easy fix.
