### ISSUE TITLE
Some materials with charge density data return None

### ISSUE THREAD

**Issue by keeganq** [materialsproject/api#703]
I am trying to retrieve a subset of the charge density data, and have found that I cannot access some materials with charge density marked as a property.

## Verison Info
**python==3.8.10**
**mp-api==0.29.3**
**emmet-core==0.38.7**

## Reproduction

First, I looked for all materials with charge density data:
```python
from mp_api.client import MPRester
from emmet.core.summary import HasProps

with MPRester("<api key>") as mpr:
    docs = mpr.summary.search(has_props = [HasProps.charge_density], fields=["material_id"])
    charge_density_mpids = [doc.material_id for doc in docs]
```

I then selected a subset of those `charge_density_mpids` to retrieve using the api. This subset included the following ids:

```python
missing_mpids = ["mp-1198805", "mp-1104237", "mp-1102616", "mp-1204636"]
```

When I try to retrieve any of the above material ids, the API returns `None`

```python
with MPRester("<api key>") as mpr:
    for mpid in missing_mpids:
        chgcar = mpr.get_charge_density_from_material_id(mpid)
        print(chgcar)
```
```
Retrieving MaterialsDoc documents: 100%|██████████| 1/1 [00:00<00:00, 24385.49it/s]
Retrieving ChgcarDataDoc documents: 0it [00:00, ?it/s]

None

Retrieving MaterialsDoc documents: 100%|██████████| 1/1 [00:00<00:00, 29127.11it/s]
Retrieving ChgcarDataDoc documents: 0it [00:00, ?it/s]

None

Retrieving MaterialsDoc documents: 100%|██████████| 1/1 [00:00<00:00, 28532.68it/s]
Retrieving ChgcarDataDoc documents: 0it [00:00, ?it/s]

None

Retrieving MaterialsDoc documents: 100%|██████████| 1/1 [00:00<00:00, 27776.85it/s]
Retrieving ChgcarDataDoc documents: 0it [00:00, ?it/s]

None
```

All appear to retrieve the MaterialsDoc but fail to retrieve ChgcarDataDoc 

## Expected Behavior

The API call should return a `pymatgen.io.vasp.outputs.Chgcar` object

**Comment by jmmshn** [comment]
So not every single material id will have a charge density.
But Co₂Ge seems like it should be in the database.
@munrojm do you know if these are present or should have been ingested?
Also, it looks like the UI indicates there is a charge density but also give you nothing when you click on "view charge density"

![image](https://user-images.githubusercontent.com/14003693/201488360-752f8d67-018c-44e9-8360-256b539b4f86.png)

**Comment by munrojm** [comment]
@keeganq @jmmshn thanks for bringing this to my attention. I will figure out what is going on.

**Comment by munrojm** [comment]
@keeganq @jmmshn This is fixed as of the latest client.

**Comment by jmmshn** [comment]
Thank you @keeganq for reporting this!
