### ISSUE TITLE
HTTP 429 errors

### ISSUE THREAD

**Issue by hanfengzhai** [materialsproject/api#720]
Hi,

I was using `mp-api` to do materials mining requesting structures from many different materials in a short time, and got the following error:

`mp_api.client.core.client.MPRestError: HTTPSConnectionPool(host='api.materialsproject.org', port=443): Max retries exceeded with url: /materials/?deprecated=False&_fields=material_id&chemsys=Xe-Ru-Ag&_limit=1000 (Caused by ResponseError('too many 429 error responses'))`

I was wondering whether this is caused by the heavy API usage or other possible reasons.

**Comment by munrojm** [comment]
Hi @hanfengzhai. You should be fine. Those are most likely due to server issues on our end. Are you still having problems with the queries?

**Comment by hanfengzhai** [comment]
Hi @munrojm, thanks for the answer! I think you are correct it works fine now:)!
