### ISSUE TITLE
limit number of materials in pymatgen.ext.matproj

### ISSUE THREAD

**Issue by EnoshI** [materialsproject/api#724]
Hello, I was just wondering if there was a way to limit the number of materials using MPrester's query function, which currently seems to gather all the materials that fit the criteria. I can't really find any info on how I would limit the collected materials.

**Comment by munrojm** [comment]
@EnoshI in the new API client, you can pass both `chunk_size` and `num_chunks` to `MPRester.summary.search` to limit the results.
