### ISSUE TITLE
Get full synthesis paragraph

### ISSUE THREAD

**Issue by ihalage** [materialsproject/api#739]
Hi, 

I want to get the full synthesis paragraph of several materials using their formulae. But I am getting only a trimmed version of the paragraph. Below is a reproducible example.

```
from mp_api.client.routes.synthesis import SynthesisRester

rester = SynthesisRester('API_KEY')
data = rester.search(target_formula='BaTiO3', chunk_size=100, num_chunks=200)

print(data[0].paragraph_string)
```

Here is the output.

> Retrieving SynthesisSearchResultModel documents: 100%|█| 314/314 [00:01<00:00, 2
> All chemicals were used without further treatment for the synthesis. BaCO3 (≥99%, Solvay), TiO2 (≥...

It's cropped. Is it possible to get the full paragraph?

**Comment by munrojm** [comment]
Unfortunately, we are only allowed to distribute excerpt text from the paragraphs that match the provided search terms under the agreement with the publishers.
