### ISSUE TITLE
How do I get the data near the VBM and CBM points？

### ISSUE THREAD

**Issue by sugarandgugu** [materialsproject/api#753]
Is there having an API to get these points？which I need to calculate the curvature.
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/95059219/222940961-78204489-00d7-47b7-baf2-d18307d7e3b3.png">

**Comment by sugarandgugu** [comment]
hello?

**Comment by munrojm** [comment]
You can pull the entire pymatgen band structure object with `MPRester.get_bandstructure_by_material_id`, and then use the `get_cbm()` and `get_vbm()` methods. The pymatgen object documentation can be found here:

https://pymatgen.org/pymatgen.electronic_structure.bandstructure.html#module-pymatgen.electronic_structure.bandstructure

**Comment by sugarandgugu** [comment]
hi!I use your method to get the class BandStructureSymmLine,but the class hasn't the eigenvals Attributes. Is the points near the CBM in this attributes? 
<img width="972" alt="image" src="https://user-images.githubusercontent.com/95059219/223094308-bd599104-232d-4783-bf75-adfde193ad86.png">

**Comment by sugarandgugu** [comment]
I mean the points near the CBM and VBM.

**Comment by munrojm** [comment]
You can use `bandstructure.bands` to get the full list of eigenvalues.

**Comment by sugarandgugu** [comment]
OK!Merci Beaucoup
