### ISSUE TITLE
Get the coordinate value of the energy band diagram

### ISSUE THREAD

**Issue by sugarandgugu** [materialsproject/api#767]
Hi! How do I get the coordinates of the picture I framed below?
<img width="1125" alt="image" src="https://user-images.githubusercontent.com/95059219/230785308-7b061d41-7572-46e5-8cd2-d391e86b29d3.png">
Is there an API that can be called, or does MPrester have a method to get the corresponding value?

**Comment by munrojm** [comment]
You can get access to the underlying band data via the pymatgen object returned by `MPRester.get_bandstructure_by_material_id`. Specifically, if the object returned is `bandstructure`, the coordinates and labels can be extracted from `bandstructure.bands`, `bandstructure.distance`, and `bandstructure.branches`

**Comment by sugarandgugu** [comment]
Thank you very much,that solved my problem！

**Comment by sugarandgugu** [comment]
Hi, I'm sorry to bother you again. If I want to get the purple point in the picture, what method should I use? I just read the document and couldn't find the relevant method.
![image](https://user-images.githubusercontent.com/95059219/231343952-ac691c40-c64a-4848-a754-8e1bf1a8ec11.png)

**Comment by munrojm** [comment]
You can access those with the `get_cbm()` and `get_vbm()` methods. Please consult the [pymatgen documentation](https://pymatgen.org/pymatgen.electronic_structure.bandstructure.html).
