### ISSUE TITLE
MPRester not working

### ISSUE THREAD

**Issue by drakeyu** [materialsproject/api#801]
Hi,

I recently cannot use MPRester from either mp_api.client or pymatgen.ext.matproj. 

the error is following:
MPRestError: REST query returned with error status code 404 on URL https://api.materialsproject.org/thermo/?thermo_types=GGA_GGA%2BU&_fields=entries&chemsys=O&_limit=143 with message:
Response {"message":"no Route matched with those values"}

It's been couple days since the last time it was working. Is there any specific update from your end so I suddenly cannot use? Thanks in advance!

**Comment by munrojm** [comment]
If you update the client it will work: `pip install mp-api --upgrade`

**Comment by keeganq** [comment]
I was having the same error and the upgrade worked for me!

**Comment by drakeyu** [comment]
Thanks! It works now.
