### ISSUE TITLE
Issue with summary.search

### ISSUE THREAD

**Issue by cpashartis** [materialsproject/api#805]
Hello again,

Is it possible there is some misconnection recently? Whenever I, or another use from my group tries to use the mprester.summary.search, we only get errors of :

`MPRestError:` REST query returned with error status code 404 on URL https://api.materialsproject.org/summary/?nelements_min=1&nelements_max=1&elements=Si&_all_fields=True&_limit=1000 with message:
Response {"message":"no Route matched with those values"}`

where this was generated with:
`mpr.summary.search(elements=['Si'], num_elements=1)`

version: 0.30.11

**Comment by GuDazi-6666** [comment]
Hello, I have encountered the same problem as yours, Have you solved it？ @cpashartis @

**Comment by cpashartis** [comment]
I have not unfortunately, I have not investigated what the issue is exactly. All I know is this should ideally work...

**Comment by GuDazi-6666** [comment]
today it works when I upgraded the package. But it mentioned that a package didn't match even it can work  properly.
I am not sure this is a correct solution.

**Comment by munrojm** [comment]
Sorry for the delayed response. Indeed, your issues can be fixed by updating the package to the latest release.

**Comment by munrojm** [comment]
It might, sometimes the repo will get a bit out of sync with the official release though. It is probably best to just install the latest release if you can. We always make sure it is compatible with the current version of the API.

**Comment by janosh** [comment]
Sounds like this is fixed in recent versions.
