### ISSUE TITLE
Option to suppress progress bar and some unneeded warnings

### ISSUE THREAD

**Issue by shyuep** [materialsproject/api#812]
The output from MPRester is too noisy, esp for Jupyter notebooks. I suggest providing at least an init arg to suppress the progress bar.

Second, some warnings are used by very few people and should not be always prompted by default. E.g.,

```
UserWarning: mpcontribs-client not installed. Install the package to query MPContribs data, or construct pourbaix diagrams: 'pip install mpcontribs-client'
```

**Comment by munrojm** [comment]
This is currently setup as an env variable, but I agree it needs to be an input arg to `MPRester`. I will add that now, and also suppress the mpcontribs warning unless that client is trying to be used.

**Comment by Jverduzc** [comment]
Hello! Has this been added to the args of MPRester?

**Comment by munrojm** [comment]
Yes, this is now in the latest release.
