### ISSUE TITLE
Broken circular dependency versions

### ISSUE THREAD

**Issue by ml-evs** [materialsproject/api#819]
Just running into an issue with MP-API very indirectly via matminer, regardingly the migration of graph hashing code from emmet to pymatgen:

```
/opt/hostedtoolcache/Python/3.8.17/x64/lib/python3.8/site-packages/emmet/core/utils.py:22: in <module>
    from pymatgen.util.graph_hashing import weisfeiler_lehman_graph_hash
E   ModuleNotFoundError: No module named 'pymatgen.util.graph_hashing'
```

matminer depends on `mp_api` indirectly via `pymatgen`, and `mp_api` depends on `emmet` and `pymatgen` itself.

A recent migration of code from emmet to pymatgen means that they can only be used together with versions `pymtagen>=2023.5.8` and `emmet>=0.57`, but this package only pins `emmet>=0.57`. Could you please consider pinning `pymatgen>=2023.5.8` explicitly too?

**Comment by ml-evs** [comment]
Here's how it appears for a user:

https://github.com/ppdebreuck/modnet/actions/runs/5299334192/jobs/9592225723?pr=154

**Comment by munrojm** [comment]
Yup, happy to change this. Thanks for the heads up.

**Comment by ml-evs** [comment]
Thanks @munrojm, hope my explanation was clear enough 😅

**Comment by tschaume** [comment]
See #825
