### ISSUE TITLE
pydantic==2 not supported, but advertised

### ISSUE THREAD

**Issue by pmrv** [materialsproject/api#824]
We ran into a small dependency problem, because something seems to have pulled in `pydantic==2`, which then triggers an error on import of `mp_api` because it imports some pydantic object from an invalid location.  You can find a full stack trace over [here](https://github.com/pyiron/pyiron_atomistics/issues/1094).  I would think the quickest fix is to add `<2` to the version spec of pydantic.

**Comment by munrojm** [comment]
Thanks for picking this out. I have just fixed this upstream in `emmet-core`.

**Comment by pmrv** [comment]
Great, thanks for the quick reply! :)
