### ISSUE TITLE
API should return error on unsupported fields

### ISSUE THREAD

**Issue by shyuep** [materialsproject/api#835]
`mpr.materials._search(nelements=2, fields=["material_id", "final_structure"])` simply returns the material_id and the final_structure is ignored. This is generally not a good behavior for people to learn that final_structure is not actually a supported field for materials.

**Comment by munrojm** [comment]
I agree with this, we should check all fields requested against `MPRester.*.available_fields` and notify people if anything they ask for is invalid.
