### ISSUE TITLE
[Bug]: Mismatch between MP website and mp elasticity route

### ISSUE THREAD

**Issue by chiang-yuan** [materialsproject/api#845]
### Version

0.33.3

### Which OS(es) are you using?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### What happened?

I am attempting to access `ElasticityDoc` by `material_id` that is bound to the computed entry on MP database. Following the example in the [Elastic Constant](https://next-gen.materialsproject.org/materials/mp-22862#elastic_constants) section on [MP website](https://next-gen.materialsproject.org/materials/mp-22862#elastic_constants) will give error of unexpected keyword argument. 

Is there specific reason why we can only access Elasticity Doc by `task_id` but not `material_id`? ([get_by_key_materials_elasticity__task_id___get](https://api.materialsproject.org/docs#/Materials%20Elasticity/get_by_key_materials_elasticity__task_id___get)) Accessing it through `task_id` is also not straightforward since we need to go through all the `task_id`s bound to certain materials and examine which is the one used for creating `ElasticityDoc`. 

It would be extremely helpful if we can access multiple ElasticityDoc through `material_id` or `material_ids`. 

### Code snippet

```python
from mp_api.client import MPRester

with MPRester(api_key="<enter your api key>") as mpr:
    elasticity_doc = mpr.elasticity.search(material_ids=["mp-22862"])
```

### Log output

```shell
TypeError: ElasticityRester.search() got an unexpected keyword argument 'material_ids'
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaume** [comment]
@chiang-yuan We released a new database version (`2024-11-14`) yesterday along with an updated client `mp-api==0.44.0`. Querying by `material_ids` is available for the elasticity endpoint:

```python
mpr.materials.elasticity.search(material_ids=["mp-22862"])
```
