### ISSUE TITLE
Entries in summary.search are returning wrongly

### ISSUE THREAD

**Issue by cpashartis** [materialsproject/api#849]
Hello,

I've noticed recently that when using summary.search, that some entries in the return data structure are not correct when compared to the website.

```python
mp_result = mpr.materials.summary.search(chemsys='Mg', energy_above_hull=(0., .5), num_sites=(0, 20))

for entry in mp_result:
    print(entry.material_id, entry.is_stable)
```

This searches for all Mg, but for some reason the entries such as mp-153 return as not stable.

**Comment by munrojm** [comment]
@cpashartis will take a closer look at this.

**Comment by tschaume** [comment]
We released a new database version (`2024-11-14`) yesterday along with an updated client `mp-api==0.44.0`. It looks like this issue is fixed:

```python
docs = mpr.materials.summary.search(
    chemsys='Mg', energy_above_hull=(0., .5), num_sites=(0, 20),
    fields=["material_id", "is_stable"]
)

for doc in docs:
    print(doc.material_id, doc.is_stable)
```

returns

```
mp-1055956 False
mp-1056351 False
mp-1056702 False
mp-1094122 False
mp-110 False
mp-1247180 False
mp-153 True
mp-973364 False
```

which is consistent with the [Materials Explorer](https://next-gen.materialsproject.org/materials?formula=Mg&is_stable=1).
