### ISSUE TITLE
`mp-api` fails to import `from maggma.utils import get_flat_models_from_model`

### ISSUE THREAD

**Issue by jan-janssen** [materialsproject/api#850]
There seems to be an version incompatibility between `mp-api` and `maggma`: 
```
from mp_api.client import MPRester
  File ".../mp_api/client/__init__.py", line 7, in <module>
    from .core import MPRestError
  File ".../mp_api/client/core/__init__.py", line 3, in <module>
    from .client import BaseRester, MPRestError
  File ".../mp_api/client/core/client.py", line 31, in <module>
    from mp_api.client.core.utils import api_sanitize, validate_ids
  File ".../mp_api/client/core/utils.py", line 7, in <module>
    from maggma.utils import get_flat_models_from_model
```

**Comment by munrojm** [comment]
The latest maggma release should be compatible. I have just updated the requirement files with the correct version minimum. A patch release should be out soon once the tests pass on main.

**Comment by liamhuber** [comment]
> The latest maggma release should be compatible. I have just updated the requirement files with the correct version minimum. A patch release should be out soon once the tests pass on main.

Would it also be possible to have this reflected [in the toml file](https://github.com/materialsproject/api/blob/e069065eefadcb8b0bcfa5c47dc36042d28ec5a7/pyproject.toml#L25)? I'm afraid I haven't used the toml system for builds so I don't know what (if any) technological side effects this would bring, but all else being equal then consistent versioning requirements across files improves readability.

**Comment by munrojm** [comment]
Yes, absolutely. I believe being quite loose with the dependency pinning in the toml file was done to prevent issues with the circular dependency of pymatgen and mp-api. This is now gone, so we can be more explicit.
