### ISSUE TITLE
What are the difference from two R2SCAN entries

### ISSUE THREAD

**Issue by Jeff-oakley** [materialsproject/api#858]
```
from mp_api.client import MPRester

mpr = MPRester(api_key)
all_entries = mpr.get_entries('mp-2858')
```

This will yield two R2SCAN entries and one GGA entry. The two R2SCAN entries seem to be identical. Are there any difference between them?

**Comment by Jeff-oakley** [comment]
I realize one is from R2SCAN, one is from GGA/GGAU/R2SCAN right? Why these two entries are exactly the same?

**Comment by munrojm** [comment]
@Jeff-oakley if the GGA/GGAU/R2SCAN mixing scheme ends up fitting to the R2SCAN hull for a particular chemical system, then the entry will be equivalent to the one in the R2SCAN only phase diagram. It only applies a correction to R2SCAN energies if adjusting to a GGA/GGA+U hull. [There is some more info on this in the docs.](https://docs.materialsproject.org/methodology/materials-methodology/thermodynamic-stability/phase-diagrams-pds)
