### ISSUE TITLE
`SummaryRester.search` does not support formulae for `chemsys` any longer?

### ISSUE THREAD

**Issue by e-kwsm** [materialsproject/api#859]
mp-api version: 0.37.5

According to the docstring of `SummaryRester.search`, `chemsys` argument may be formulae.

https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/materials/summary.py#L93-L94

However it does not work&mdash;the following prints `0 26`:

```python
import warnings
from pymatgen.ext.matproj import MPRester

warnings.filterwarnings("ignore")

MP_API_KEY = ...  # key for new API
with MPRester(MP_API_KEY) as mpr:
    r_c = mpr.summary.search(chemsys="Fe2O3")
    r_f = mpr.summary.search(formula="Fe2O3")
    print(len(r_c), len(r_f))  # 0 26
    # chemical system works as expected
    r_c_cs = mpr.summary.search(chemsys="Fe-O")
    # print(len(r_c_cs))  # 136
```

Is the docstring outdated?

**Comment by munrojm** [comment]
Yes, it should specify that only `formula` will accept single formula entries.

**Comment by e-kwsm** [comment]
The same goes for the followings?
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/bonds.py#L58-L59
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/molecules.py#L122-L123
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/orbitals.py#L87-L88
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/partial_charges.py#L52-L53
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/partial_spins.py#L52-L53
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/redox.py#L60-L61
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/summary.py#L55-L56
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/summary.py#L55-L56
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/thermo.py#L82-L83
https://github.com/materialsproject/api/blob/47fc6087da8253f55adb101b5df3251b6347b2ac/mp_api/client/routes/molecules/vibrations.py#L67-L68
