### ISSUE TITLE
How to obtain the k_vrh and g_vrh of the material

### ISSUE THREAD

**Issue by dream123321** [materialsproject/api#867]
### Problem

    with MPRester("API_KEY") as mpr:
        docs = mpr.materials.summary.search(material_ids=['mp-66'],fields=['elements','k_vrh','g_vrh','band_gap'])

    i = docs[0]
    print(i.elements)
    print(i.band_gap)

Result:
[Element C]
4.1145

But add it after the code:
print(i.k_vrh)

Result:
  File "/home/jh/mp/test.py", line 22, in <module>
    print(i.k_vrh)
  File "/home/jh/anaconda3/envs/mp_test/lib/python3.10/site-packages/mp_api/client/core/client.py", line 925, in new_getattr
    raise AttributeError(
AttributeError: 'MPDataDoc' object has no attribute 'k_vrh'

### Proposed Solution

How to obtain the k_vrh and g_vrh of the material?

**Comment by munrojm** [comment]
[See this thread](https://matsci.org/t/not-able-to-retrieve-elasticity-data/51990/7)

**Comment by dream123321** [comment]
> [See this thread](https://matsci.org/t/not-able-to-retrieve-elasticity-data/51990/7)

Thank you very much!
