### ISSUE TITLE
MPRester.get_entries returned inconsistent results

### ISSUE THREAD

**Issue by goodwilling** [materialsproject/api#873]
-------------script starts-------------------
from mp_api.client import MPRester

mpr = MPRester("32-digit API key")
entries = mpr.get_entries("mp-546794", inc_structure=None, 
             property_data=["material_id", "composition", "energy_above_hull"], #sort_by_e_above_hull=True,
             additional_criteria={"thermo_types": ["GGA_GGA+U"]})
-------------script ends-------------------

The above script returned the entry of mp-546794 with energy_above_hull = 0.0. However, using mpr.summary.search
or referring to the web site of mp-546794 shows the energy_above_hull of mp-546794 is 0.005647450555557043 or 0.006.

**Comment by munrojm** [comment]
The summary energy above hull data is pulled from the `GGA/GGA+U/R2SCAN` hull which is probably where this difference is.
