### ISSUE TITLE
no validator found for <class 'pymatgen.core.composition.Composition' during import of MPRester

### ISSUE THREAD

**Issue by dembart** [materialsproject/api#876]
import of PropertyDoc from emmet.core.material_property fails due to the RuntimeError: no validator found for <class 'pymatgen.core.composition.Composition'>. 

Any ideas how to fix it? I am running code on M1 Mac with Ventura OS

---> 26 from emmet.core.material_property import PropertyDoc
     27 from emmet.core.mpid import MPID
     28 
...
[~/opt/anaconda3/lib/python3.8/site-packages/pydantic/fields.cpython-38-darwin.so](https://file+.vscode-resource.vscode-cdn.net/Users/artemdembitskiy/Downloads/~/opt/anaconda3/lib/python3.8/site-packages/pydantic/fields.cpython-38-darwin.so) in pydantic.fields.ModelField.populate_validators()

[~/opt/anaconda3/lib/python3.8/site-packages/pydantic/validators.cpython-38-darwin.so](https://file+.vscode-resource.vscode-cdn.net/Users/artemdembitskiy/Downloads/~/opt/anaconda3/lib/python3.8/site-packages/pydantic/validators.cpython-38-darwin.so) in find_validators()

RuntimeError: no validator found for <class 'pymatgen.core.composition.Composition'>,

**Comment by munrojm** [comment]
Which version of emmet-core, mp-api, and pymatgen are you running with?

**Comment by dembart** [comment]
emmet-core==0.68.0

**Comment by tschaume** [comment]
Seems to be fixed and working with the following versions at least.

```
emmet-core==0.84.3rc6
mp-api==0.44.0
pymatgen==2024.11.13
```
