### ISSUE TITLE
Downloaded structures differ from structures on Materials Project

### ISSUE THREAD

**Issue by cote3804** [materialsproject/api#881]
Trying to download entry mp-13 (BCC Fe) results in a non-cubic unit cell that differs from the same entry that can be found [here](https://next-gen.materialsproject.org/materials/mp-13?formula=Fe)

Here is the code: 
```
structure = mpr.get_structure_by_material_id("mp-13")
structure.to_file("POSCAR_API", fmt='poscar')
```
This writes a POSCAR file that looks like this in VESTA: 
![image](https://github.com/materialsproject/api/assets/101949243/68c787d6-0066-4d69-a77b-ba9650d1758a)

Using the materials project website, the CIF I download looks like this:
![image](https://github.com/materialsproject/api/assets/101949243/770c7806-5f5b-4502-ac48-3740214713c8)

It is not just this one material entry that is giving me this problem. Entry mp-101 also causes issues. Downloading the structure via mp-api gives this structure:
![image](https://github.com/materialsproject/api/assets/101949243/3d94a7e6-e9c7-43ad-9987-a5f6c9c17717)

Whereas using the website I get this structure, which not only has a different unit cell but also includes atoms that the mp-api structure does not.
![image](https://github.com/materialsproject/api/assets/101949243/3e1b22e4-8438-4aa6-8f60-5089faa3436a)

I'm using mp-api version 0.39.5 and pymatgen 2024.2.8 with python version 3.9.7

**Comment by benrich37** [comment]
Just downloaded the same material by the same method and ran into the same error, currently using version mp-api version 0.33.3

**Comment by munrojm** [comment]
`structure = mpr.get_structure_by_material_id("mp-13", conventional_unit_cell=True)` should get you the conventional cubic cell.
