### ISSUE TITLE
How to open the .json file in python

### ISSUE THREAD

**Issue by xiaowangfeng** [materialsproject/api#898]
when i want to visualize materials_Li_Fe_V.json，i don’t know how to do 

Is there a package or code that can help me do this

**Comment by minhsueh** [comment]
Please specify your question, but here is something for you:
1. to open JSON, Python has a standard library: https://docs.python.org/3/library/json.html
2. Visualizing it depends on the data in your file and what you want. So, again, please specify your problem.
