### ISSUE TITLE
[Feature Request]: Include a README badge of the supported Python versions

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [materialsproject/api#901]
### Problem

Most of the MP software stack has some basic information on the README about the supported Python versions. However, `mp-api` doesn't have this. Users running on Python 3.8 might not realize that they can't access newer versions of `mp-api` unless they upgraade Python.

### Proposed Solution

Update the README to have a Python version badge.

**Comment by munrojm** [comment]
Done
