### ISSUE TITLE
[Bug]: ValidationError 6 validation errors for MoleculeSummaryDoc builder_meta.build_date

### ISSUE THREAD

**Issue by funihang** [materialsproject/api#922]
### Code snippet

```python
from mp_api.client import MPRester

with MPRester(api_key) as mpr:
    docs = mpr.molecules.summary.search()
```

### What happened?

I am attempting to get molecules from API using the attached code. It can work at first, but when the progress bar reaches 155361/221598, an error will be reported. Could you please check it?

### Version

mp-api 0.41.2

### Which OS?

- [ ] MacOS
- [X] Windows
- [ ] Linux

### Log output

```shell
ValidationError: 6 validation errors for MoleculeSummaryDoc
builder_meta.build_date
  Value error, Invalid isoformat string: '2023-11-07T22:35:04.718Z' [type=value_error, input_value={'$date': '2023-11-07T22:35:04.718Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
last_updated
  Input should be a valid datetime [type=datetime_type, input_value={'$date': '2023-11-07T22:35:04.718Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/datetime_type
origins.0.last_updated
  Value error, Invalid isoformat string: '2020-11-11T12:51:27.833Z' [type=value_error, input_value={'$date': '2020-11-11T12:51:27.833Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
origins.1.last_updated
  Value error, Invalid isoformat string: '2023-08-03T18:52:51.206Z' [type=value_error, input_value={'$date': '2023-08-03T18:52:51.206Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
origins.2.last_updated
  Value error, Invalid isoformat string: '2020-11-11T12:51:27.833Z' [type=value_error, input_value={'$date': '2020-11-11T12:51:27.833Z'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
has_props
  Input should be a valid list [type=list_type, input_value={'materials': True, 'ther...lse, 'substrates': True}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/list_type
```

**Comment by munrojm** [comment]
I will investigate this. For now, you can pass `use_document_model=False` to `MPRester` to fix the issue. Note the data will. be returned as dictionaries instead of `MPDataDoc` objects.

**Comment by funihang** [comment]
> I will investigate this. For now, you can pass `use_document_model=False` to `MPRester` to fix the issue. Note the data will. be returned as dictionaries instead of `MPDataDoc` objects.

Thanks for your reply. I reinstalled my conda env and downgraded python version to 3.8. It works now, although I'm unsure which step resolved the issue.

**Comment by kavanase** [comment]
Just to bump this, I'm also running into the same issue. Setting `fields=["structure"]` (all I need in this case) avoids it.

**Comment by tschaume** [comment]
@kavanase I just released mp-api `v0.44.0rc0` with a (temporary) fix for this. Could you give it a try? Thanks! Note that we've fixed the data behind the scenes already and this error shouldn't show up when you include a query (e.g. on `nelements`). Only full downloads without an explicit query are affected when using previous versions of the client.

**Comment by kalvdans** [comment]
@tschaume can you link to the PR that fixed the issue?

**Comment by tschaume** [comment]
@kalvdans it would be PR #947 but I'd consider it a temporary fix since I simply disabled the rerouting of full download requests from our MongoDB to our [OpenData repositories](https://docs.materialsproject.org/downloading-data/aws-opendata). We're working on sync'ing the data in the OpenData repo and should be able to revert #947 with the upcoming data release. HTH.

**Comment by tschaume** [comment]
Try using the officially supported `mp_api` client:

```python
from mp_api.client import MPRester

with MPRester() as mpr:
    docs = mpr.molecules.summary.search(nelements=7)
```

We generally recommend not mixing the pymatgen and mp_api clients.

**Comment by tschaume** [comment]
Which `emmet-core` version are you running? You might have to upgrade `emmet-core` since it contains the model definitions used for validation.

**Comment by kavanase** [comment]
I was using `emmet-core-0.84.2rc4`, now have tried with the latest PyPI release (`emmet-core-0.84.2`), and still getting the same error

**Comment by tschaume** [comment]
Thanks for checking @kavanase! We're in the middle of preparing a new data release that will hopefully fix it. We'll get back to you.

**Comment by tschaume** [comment]
@kalvdans @kavanase The new data release v2024.11.14 is out and the `mp-api` library updated accordingly. Upgrading to `mp-api==0.44.0` should fix the issue.
