### ISSUE TITLE
[Bug]: pydantic 2.10.0 breaks mp-api

### ISSUE THREAD

**Issue by SiLiKhon** [materialsproject/api#941]
### Code snippet

```python
### on google colab: 
# !pip uninstall -y pydantic pydantic_core
# !pip install mp-api  # observe that pydantic-2.10.0 gets installed

from mp_api.client import MPRester

with MPRester("...") as mpr:
    docs = mpr.materials.summary.search(material_ids=["mp-950995"])
```

### What happened?

1. install `mp-api` in a clean environment
2. for some reason, `pydantic 2.10.0` gets installed as a dependency
3. broken `mp-api`

### Version

0.42.2

### Which OS?

- [ ] MacOS
- [ ] Windows
- [X] Linux

### Log output

```shell
/usr/local/lib/python3.10/dist-packages/mp_api/client/core/client.py in _generate_returned_model(self, doc)
   1073         )
   1074 
-> 1075         data_model.model_fields = {
   1076             **{
   1077                 name: description

AttributeError: can't set attribute 'model_fields'
```

**Comment by saj3sh** [comment]
i am also getting same issue

**Comment by SiLiKhon** [comment]
Note: downgrading back to `pydantic==2.9.2` should fix the issue (at least, with `mp-api==0.42.2`)

**Comment by PythonFZ** [comment]
Can replicate as well

**Comment by tschaume** [comment]
@SiLiKhon @saj3sh @PythonFZ I just pushed a release candidate to PyPI: https://pypi.org/project/mp-api/0.43.0rc1/. Give it a try and let me know if you notice any issues. Thanks!

**Comment by SiLiKhon** [comment]
Thanks @tschaume !
I tried `!pip install mp-api==0.43.0rc1` on colab, and it works fine with both new pydantic 2.10.0 and 2.10.1.
