### ISSUE TITLE
[DOC] Usage of environment variables (`MP_API_KEY` and `PMG_MAPI_KEY`) for setting API key is not documented?

### ISSUE THREAD

**Issue by DanielYang59** [materialsproject/api#949]
As far as I could tell, the usage of env var for setting the API key is not quite visible:
- The [Materials Project API](https://next-gen.materialsproject.org/api) page should have mentioned this?
- The [Differences between new and legacy API](https://docs.materialsproject.org/downloading-data/differences-between-new-and-legacy-api) form doesn't mention these two environment variables either
- [Materials Project Documentation](https://docs.materialsproject.org/) doesn't seem to have recording for `PMG_MAPI_KEY` at all
![image](https://github.com/user-attachments/assets/1d0fad32-e9a6-40f6-ab7c-d0a2a3030b99)
- AFAIK, only the [docstring for `mp_api.client.mprester.MPRester`](https://materialsproject.github.io/api/_autosummary/mp_api.client.mprester.MPRester.html) mentioned `MP_API_KEY`:
    > If this is None, the code will check if there is a “MP_API_KEY” setting. If so, it will use that environment variable.

---

- It seems setting `MP_API_KEY` as env var doesn't work (for the legacy `from pymatgen.ext.matproj import MPRAester`), and need to pass to directly to `MPRester()`? 

```python
import os

from pymatgen.ext.matproj import MPRester


assert (api_key := os.getenv("MP_API_KEY")) and len(api_key) == 16

mpr = MPRester()
entries = mpr.get_pourbaix_entries(["Cu"])  # TypeError: 'NoneType' object is not callable
```

**Comment by tschaume** [comment]
Thanks @DanielYang59! Using env vars for the python client(s) could definitely use a little more documentation.

- I don't think that code-related instructions like this should live on our website. They belong into our dedicated docs page. I might look into thinning out the API page on our website.
- Would you mind using the "Edit on Github" button in our docs and update the page that you think should have more information about it?
- Yes, the legacy rester only recognizes the `PMG_MAPI_KEY` env var. Also supporting `MP_API_KEY` would be a request for the pymatgen forum or repo.

**Comment by DanielYang59** [comment]
Hi @tschaume thanks a ton for the quick reply.

> Would you mind using the "Edit on Github" button in our docs and update the page that you think should have more information about it?

Sorry I don't know much about the overall structure (and philosophy) of the docs page, so perhaps I would prefer to leave this to you?

Another thing I find annoying is that the API pages seem to redirect to one another very often

> Yes, the legacy rester only recognizes the PMG_MAPI_KEY env var. Also supporting MP_API_KEY would be a request for the pymatgen forum or repo.

Okay I'm happy to push a PR to `pymatgen` to implement this. I just had a quick look at the PMG implementation and indeed it looks like it would only try to pick up the new key when it's not provided as arg: 
- https://github.com/materialsproject/pymatgen/blob/31f1e1fb8cc1bb517d59ea8e484965bb641c42a0/src/pymatgen/ext/matproj_legacy.py#L174-L177

Would you mind if I ping you on that PR from PMG's side for some quick comment (I understand MP_API is separately maintained from PMG), but just some quick confirmation in case I break anything would be really helpful :)

**Comment by tschaume** [comment]
> Sorry I don't know much about the overall structure (and philosophy) of the docs page, so perhaps I would prefer to leave this to you? Another thing I find annoying is that the API pages seem to redirect to one another very often

For both of these it would be super valuable to us to get your take on how to update our docs. If you edit on Github it'll result in a PR that I can review. You'd help us get the balling rolling :)

>  I would submit a request to clarify this.

I'll comment in the pymatgen thread to clarify. And yes, it's ok to tag me if something needs my attention.

**Comment by DanielYang59** [comment]
@tschaume Hi sorry for the lack of response, I'm currently looking for a good home for the environment variable and it appears to me it should belong to either:
- the [Accessing Data](https://next-gen.materialsproject.org/api#accessing-data) section of the `The Materials Project API` page
- Or perhaps the [Materials Project API Docs.](https://next-gen-docs.materialsproject.org/downloading-data/how-do-i-download-the-materials-project-database) which is pointed to as "For detailed instructions on how to use the API to download data, please see the [Materials Project API Docs.](https://next-gen-docs.materialsproject.org/downloading-data/how-do-i-download-the-materials-project-database)"
- Or [Query and Download Contributed Data](https://docs.materialsproject.org/downloading-data/query-and-download-contributed-data)?

I would be happy with either one as I guess a quick mention of the existence of such environment variable should do the job? What do you think?

**Comment by tschaume** [comment]
Thanks @DanielYang59. I think the [Getting Started](https://docs.materialsproject.org/downloading-data/using-the-api/getting-started) page is the best place for this.

**Comment by DanielYang59** [comment]
Beautiful that looks great, looks like a quick mention there should suffice. I would add a PR for this and feel free to tweak it :) Thanks!
